server:
   port: 9888
es:
   port: 9200
   hosts: 47.115.34.118,8.129.173.185,8.129.172.251
   scheme: http
   cluster:
      name: famiao-cluster
   index:
      shards: 3
      replicas: 1
spring:
   datasource:
      hikari:
         master:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/famiao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
            username: root
            password: ntVklfM5@VMj2pHd
            idleTimeout: 60000
            connectionTimeout: 60000
            validationTimeout: 3000
            loginTimeout: 5
            maxLifetime: 60000
         slave:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/famiao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
            username: root
            password: ntVklfM5@VMj2pHd
            idleTimeout: 60000
            connectionTimeout: 60000
            validationTimeout: 3000
            loginTimeout: 5
            maxLifetime: 60000
logging:
   level:
      com.famiao.search: debug
dynamic:
   sql:
      path: D:\Env\project\fm-search\src\main\resources\template\DynamicSqlTemplete.xml
   settings:
      path: D:\Env\project\fm-search\src\main\resources\template\Settings.json
   cron:
      expression: 0 0/20 * * * ?